### PR TITLE
Rubyonracetracks

### PR DESCRIPTION
**Pull request by jhsu802701**
Added instructions on how to set up Rails.MN with Docker
Updated the Rails installation page with the Docker way of getting started in Ruby on Rails
Added the credentials.sh script for entering GitHub credentials
Added the build.sh script for building Rails.MN locally
Added the server.sh script for starting the local server

### CODE REVIEW

**Comment by tamouse** [comment]
I have no idea why you think you need Docker to modify a quite simple Jekyll site.

**Comment by jhsu802701** [comment]
Jekyll is simple to use, but installing it requires Ruby plus gem capability.  In my Docker images, the elements are rbenv + the latest version of Ruby + "gem install jekyll".  Since I rely on Docker for my standard Ruby on Rails setup, it carries over to Jekyll.  Of course, use of Docker is optional.  While Jekyll isn't finicky like Rails, Ruby on Rails has taught me not to take anything for granted and to make sure that there's always a standard working development environment available on my watch.  (In my opinion, it's better to have this option and not need it than the other way around.)

**Comment by tamouse** [comment]
You can run it however you wish, I'm not interested in adding a bunch of things that are irrelevant for everyone else. There is *no* ruby development going on in this repo, it can be used by any system level ruby installation, bundling gems is a simple process. The only "development" is writing text for the pages, and you only need ruby and jekyll if you want to preview the changes locally.

**Comment by jhsu802701** [comment]
Do you want me to submit a new branch with the other changes?  The other changes I submitted were the Bash scripts (which people are free to ignore) and the link to the VirtualBox/Docker way of installing Ruby on Rails.

**Comment by tamouse** [comment]
Submit a new PR with the changes for `installation/index.md`.

**Pull request closed without merging**
